version: '3.7'

services:
  db-mysql:
    container_name: db-mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=db_score_tracker
    volumes:
      - mysql-data:/var/lib/mysql

  score-tracker-app:
    container_name: score-tracker-app
    image: score-tracker:1.0
    ports:
      - "8080:8080"
    depends_on:
      - db-mysql
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=admin
      - DB_URL=jdbc:mysql://db-mysql:3306/db_score_tracker

volumes:
  mysql-data:
